# Generated by Django 5.1.4 on 2024-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attackForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='interface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='packets',
            field=models.PositiveBigIntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='server_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='sip_server_ip_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='sip_username_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attack',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
